name: Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run the tests
      run: |
        go test
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    
    - name: Publish doc to go.dev packages
      run: |
        git pull
        export COMMIT=`git rev-parse HEAD`
        export TAG=$(git describe --exact-match --abbrev=0 --tags ${COMMIT} 2> /dev/null || true)
        if [ -z "$TAG" ]; then
          export VERSION=$COMMIT
        else
          export VERSION=$TAG
        fi
        curl https://proxy.golang.org/github.com/mhkarimi1383/goAPIBaseProject/@v/$VERSION.info