name: publish

on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & Push Docker image
      run: |
        docker build . --tag ghcr.io/mhkarimi1383/go-api-base-project:latest --tag ghcr.io/mhkarimi1383/go-api-base-project:${GITHUB_SHA:0:8}
        docker push ghcr.io/mhkarimi1383/go-api-base-project:latest
        docker push ghcr.io/mhkarimi1383/go-api-base-project:${GITHUB_SHA:0:8}
